name: linter-check

on: push

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and tests
        run: |
          make lint
          make test        
        
  coverage:
    needs: [ check ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - run: |
          pip install poetry
          make install
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 268149fdc01b007176e8039f4ddfa1fa24d6596ddc2d759bde00b525a5f2c1d6
      with:
        coverageCommand: make test-coverage
